ERROR - 2025-06-27 13:50:22 --> Error connecting to the database: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �BRASAS�
CRITICAL - 2025-06-27 13:50:22 --> Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �BRASAS�
#0 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM "...', Array, false)
#2 C:\xampp\htdocs\dfpyme\system\Validation\Rules.php(104): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\dfpyme\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_not_unique('1220', 'pinusuario_sist...', Array, NULL)
#4 C:\xampp\htdocs\dfpyme\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('pin', 'pin', '1220', Array, Array)
#5 C:\xampp\htdocs\dfpyme\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\dfpyme\app\Controllers\login\loginController.php(19): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\login\loginController->login()
#8 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\loginController))
#9 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2025-06-27 13:50:37 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM &quot;estado_licencia&quot;
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #148, 'SELECT "estado_...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "estado_...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "estado_...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "estado_...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Controllers\login\loginController.php(32): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\login\loginController->login()
#9 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\loginController))
#10 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-06-27 13:50:37 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM &quot;estado_licencia&quot;
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #148, 'SELECT "estado_...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "estado_...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "estado_...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "estado_...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Controllers\login\loginController.php(32): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\login\loginController->login()
#9 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\loginController))
#10 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-06-27 14:19:54 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\dfpyme\app\Controllers\factura_electronica\FacturaElectronica.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 31)
#1 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\factura_electronica\FacturaElectronica->pre_factura()
#2 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\factura_electronica\FacturaElectronica))
#3 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2025-06-27 14:20:14 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\dfpyme\app\Controllers\factura_electronica\FacturaElectronica.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 31)
#1 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\factura_electronica\FacturaElectronica->pre_factura()
#2 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\factura_electronica\FacturaElectronica))
#3 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2025-06-27 15:19:17 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para integer: «»
LINE 1: ... '10000', '0', '20307', 0, '222222222222', ('381'), '1', '')
                                                                    ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #158, 'INSERT INTO "pa...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "pa...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "pa...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "pa...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\dfpyme\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\dfpyme\app\Controllers\factura_electronica\FacturaElectronica.php(498): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\factura_electronica\FacturaElectronica->pre_factura()
#10 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\factura_electronica\FacturaElectronica))
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2025-06-27 15:19:17 --> pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para integer: «»
LINE 1: ... '10000', '0', '20307', 0, '222222222222', ('381'), '1', '')
                                                                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #158, 'INSERT INTO "pa...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "pa...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "pa...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "pa...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\dfpyme\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\dfpyme\app\Controllers\factura_electronica\FacturaElectronica.php(498): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\factura_electronica\FacturaElectronica->pre_factura()
#10 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\factura_electronica\FacturaElectronica))
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2025-06-27 15:19:17 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\dfpyme\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\dfpyme\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\dfpyme\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\dfpyme\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\dfpyme\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-06-27 15:19:41 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para integer: «»
LINE 1: ... '10000', '0', '20308', 0, '222222222222', ('381'), '1', '')
                                                                    ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #158, 'INSERT INTO "pa...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "pa...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "pa...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "pa...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\dfpyme\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\dfpyme\app\Controllers\factura_electronica\FacturaElectronica.php(498): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\factura_electronica\FacturaElectronica->pre_factura()
#10 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\factura_electronica\FacturaElectronica))
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2025-06-27 15:19:41 --> pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para integer: «»
LINE 1: ... '10000', '0', '20308', 0, '222222222222', ('381'), '1', '')
                                                                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #158, 'INSERT INTO "pa...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "pa...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "pa...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "pa...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\dfpyme\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\dfpyme\app\Controllers\factura_electronica\FacturaElectronica.php(498): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\factura_electronica\FacturaElectronica->pre_factura()
#10 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\factura_electronica\FacturaElectronica))
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2025-06-27 15:19:41 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\dfpyme\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\dfpyme\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\dfpyme\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\dfpyme\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\dfpyme\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2025-06-27 19:48:44 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\dfpyme\app\Controllers\caja_general\cajaGeneralController.php(1046): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 1046)
#1 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\caja_general\cajaGeneralController->exportVentas()
#2 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\caja_general\cajaGeneralController))
#3 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2025-06-27 20:39:47 --> Cannot access offset of type string on string
#0 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\caja_general\cajaGeneralController->exportVentas()
#1 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\caja_general\cajaGeneralController))
#2 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2025-06-27 20:42:45 --> Maximum execution time of 120 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-06-27 21:22:25 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 21:22:25 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 21:27:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 21:27:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 21:32:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 21:32:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 21:37:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 21:37:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 21:42:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 21:42:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 21:47:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 21:47:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 21:52:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 21:52:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 21:57:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 21:57:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 22:02:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:02:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 22:07:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:07:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 22:12:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:12:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 22:17:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:17:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 22:22:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:22:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 22:27:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:27:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 22:32:25 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:32:25 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:36:55 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\dfpyme\app\Controllers\caja_general\cajaGeneralController.php(1046): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 1046)
#1 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\caja_general\cajaGeneralController->exportVentas()
#2 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\caja_general\cajaGeneralController))
#3 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2025-06-27 22:37:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:37:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 22:42:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:42:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 22:47:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:47:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:47:55 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\dfpyme\app\Controllers\caja_general\cajaGeneralController.php(1046): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 1046)
#1 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\caja_general\cajaGeneralController->exportVentas()
#2 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\caja_general\cajaGeneralController))
#3 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2025-06-27 22:50:17 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\dfpyme\app\Controllers\caja_general\cajaGeneralController.php(1046): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 1046)
#1 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\caja_general\cajaGeneralController->exportVentas()
#2 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\caja_general\cajaGeneralController))
#3 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2025-06-27 22:52:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:52:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:52:39 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\dfpyme\app\Controllers\caja_general\cajaGeneralController.php(1046): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 1046)
#1 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\caja_general\cajaGeneralController->exportVentas()
#2 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\caja_general\cajaGeneralController))
#3 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2025-06-27 22:57:25 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 22:57:25 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 23:02:25 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 23:02:25 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 23:22:39 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 23:22:39 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 23:27:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 23:27:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 23:32:25 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 23:32:25 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 23:37:25 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 23:37:25 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 23:40:56 --> Cannot access offset of type string on string
#0 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\caja_general\cajaGeneralController->exportVentas()
#1 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\caja_general\cajaGeneralController))
#2 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2025-06-27 23:42:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 23:42:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 23:44:39 --> Cannot access offset of type string on string
#0 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(832): App\Controllers\caja_general\cajaGeneralController->exportVentas()
#1 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\caja_general\cajaGeneralController))
#2 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\dfpyme\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2025-06-27 23:47:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 23:47:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 23:52:24 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 23:52:24 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2025-06-27 23:57:25 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^ in C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2025-06-27 23:57:25 --> pg_query(): Query failed: ERROR:  no existe la relación «estado_licencia»
LINE 2: FROM "estado_licencia"
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135)
#1 C:\xampp\htdocs\dfpyme\system\Database\Postgre\Connection.php(135): pg_query(Resource id #190, 'SELECT "id_clie...')
#2 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_clie...')
#3 C:\xampp\htdocs\dfpyme\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_clie...')
#4 C:\xampp\htdocs\dfpyme\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "id_clie...', Array, false)
#5 C:\xampp\htdocs\dfpyme\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\dfpyme\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\dfpyme\app\Commands\SyncLicencias.php(20): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\dfpyme\system\CLI\Commands.php(63): App\Commands\SyncLicencias->run(Array)
#9 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('sync:licencias', Array)
#10 C:\xampp\htdocs\dfpyme\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'sync:licencias')
#12 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\dfpyme\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\dfpyme\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\dfpyme\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
